apiVersion: skaffold/v1alpha1
kind: Config
build:
  artifacts:
  - imageName: gcr.io/r2d4minikube/skaffold
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
    - paths:
      - deploy/skaffold/*
      parameters:
        IMAGE_NAME: gcr.io/r2d4minikube/skaffold
