steps:
# Build the container that will do the go build.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--target', 'build', '-t', 'builder', '-f', 'deploy/skaffold/Dockerfile', '.']
# Do the go build.
  - name: 'builder'
    args: ['make', 'cross']
# Upload to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'out/skaffold-*', 'gs://skaffold/builds/$COMMIT_SHA/']
# Bump the latest build
# Upload to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'gs://skaffold/builds/$COMMIT_SHA/*', 'gs://skaffold/builds/latest/']
